checks:
  javascript: true
filter:
  excluded_paths:
    - test/*
    - node_modules/*
    - build/*
    - docs/*

build:
  environment:
    node: 8.1.0

  dependencies:
    before:
      - npm install grunt-cli -g
      - npm install
      - node_modules/protractor/bin/webdriver-manager update

  tests:
    override:
      -
        command: 'grunt coverage'
        coverage:
          file: 'build/coverage/clover.xml'
          format: 'clover'
