sudo: required

cache:
    npm: false
language: node_js
node_js:
- node
before_install: npm install -g npm
before_script:
- npm install -g grunt-cli npm
- npm install
env:
  global:
    secure: DfHvi6Jg6vXSCsdiB29pb1l315BEla5Pbfmr3t30n8p1OU2qeu1+PfaGwXv+vUvN3dQ81q7W9eN6aF1nPD+npibF8wd+xhSrLUE81wHIGfEWk7ZNO4p1t6Lx19PjYTCJLo5Oq+j6ceWrW2M9Vn4udvH2BkTrwjBSRTOIZQYHFw91R8MKT6jadKmnnb7bEWpjm7MBeTdf0jxcJIYlR4ydPHmE6+UEMYxa4RvM8GnBnbFwxygl+G9cduh8kPo/QgHFRBtEfdCjHpn5RooWz+xCvobgY3znvnrEZlj5f/AUxTdFjkdkfesA5IfgWqtaNwFBlvHtIwam8+9tLjBElbgVjVxoUiH+qB6atZshlOTbfSktH5pAdcHLNqan2nl/iHw7FsahWb1IzrZNBA/aEna2NqsEzuNjYz/68u7S//qQc6XR67wh6WBrR844uC1WF3DRGqkqtUmlVWA3wbKq61mksBtTtp+yGXQhklr5tz4nDfFwB6gkgKjSwJpt2SpTyp67Ce1mhJDHqVtlV1JgTNHCua/nw4k50tNeFCTZByL5o7V7ys0a7nAE0g7cvy6cCM0x9ihe+ZKyQvjHsBfKdYRTR2zIWMYzUtrOEwrAZl8cR5ITplXH0d6pRTmpaHh2JiT2wM9NHIcqSIQBGXtZtCrnshLChY3lg2n1OFdpGWjoUJE=
