sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- node
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm install -g grunt-cli npm
- npm install
- node_modules/protractor/bin/webdriver-manager update --gecko=false
env:
  global:
    secure: OAg/k+C69Hm9qVkC9OaHD5vCD4WR+mTAWm1A0iFDzD651+3TOawn4Fh66dbNPwX+VIPDCUmnqHYGJ/1chZEhHy2x7Jzj+FNdqDZRjA8WYcobRGUVVmu2+sz01ZgyNb4SmOpDAEs9Sjc2xX4cMDACUq3gQP0CnFHv7CnF5h/ojT3GRTbf7aVPrrNgo9oDa0m2xj3qO8iNY4uS8ieTm+rFPcvnZR4gosKnaJ6lX3psj+3Q4bDCF40R26RVHLWybV3kqjzsWwtLK30QM3e/ji1r2XHTcwIb8sO8EaMxUsJYJiHfU4veClB1kyCvFJ9IJZJhb/WjdJSijU8NaUQ/f3+3r8VL90/AYvb6P7+oOjIKTbjFdNy768EF+jMXLCuNuKp8jf//8m3VzDUltgomPdvVSTeKEoawyP0s7gJi+TTdgatp5yP9ZHXXCGQis/Zx9xjENnAtmJEPgp+r38vh0elz4JHimG80oD5EBo8yQwMLZl3lrmq8FM5HS5HVrFMfVmsjNgYEau2/9n1ZX2n2eP6d53B9GumJeaDawMd9uY8LgXmTLd0h5NDHwcdRKkIAtMLvTe9OhlY4iq2z8zX2L1L1oHjp6tqftnz+n62EJnvbPEOK5pvkifxLS7LVOk8lQvRVLaGF7B4H2F84gVq+bmWFynvXlvywBYfMkLK52qNAb9I=
